name: Barrion PR Check
on:
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Setup Gradle
        run: |
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options=-Xmx2g" >> gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
      
      - name: Run Lint
        run: ./gradlew lint
      
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      
      - name: Check Compilation
        run: ./gradlew compileDebugSources
      
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      
      # v4 버전 사용
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: barrion-debug
          path: app/build/outputs/apk/debug/app-debug.apk
