name: Barrion PR Check
on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ===== CI (Continuous Integration) 부분 =====
      # 코드 가져오기
      - uses: actions/checkout@v4

      # 자바 개발 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle 설정 및 AndroidX 설정 추가
      - name: Setup Gradle and AndroidX
        run: |
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options=-Xmx2g" > gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties

      # local.properties 파일 생성
      - name: Create local.properties
        run: touch local.properties

      # APK 빌드
      - name: Build Debug APK
        run: ./gradlew assembleDebug --warning-mode=all
        continue-on-error: true

      # ===== CD (Continuous Delivery) 준비 부분 =====
      # 빌드 결과물 저장
      - name: Upload APK
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: barrion-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: ignore